title: Summer School on Geometric Representation Theory
description: 9 July&mdash;13 July 2018, Institute of Science and Technology Austria
show_downloads: false
google_analytics:
theme: 

kramdown:
  parse_block_html: true
